<?php
require_once '../../config/database.php';
require_once '../../vendor/autoload.php'; // Make sure autoload includes dompdf

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Border;
use Dompdf\Dompdf;
use Dompdf\Options;

if (!isset($_SESSION['admin_id'])) {
    header("Location: ../login.php");
    exit();
}

// Get filter parameters
$start_date = $_GET['start_date'] ?? date('Y-m-01');
$end_date = $_GET['end_date'] ?? date('Y-m-t');
$kelas = $_GET['kelas'] ?? '';
$jurusan = $_GET['jurusan'] ?? '';
$siswa_id = $_GET['siswa_id'] ?? '';
$status = $_GET['status'] ?? '';
$format = $_GET['format'] ?? 'pdf'; // Default format is PDF

// Base query for fetching attendance data
$sql = "SELECT a.id, a.tanggal, a.jam_masuk, a.status, a.keterangan, a.approval_status, 
         s.nama_lengkap, s.nis, s.kelas, s.jurusan 
        FROM absensi a
        JOIN siswa s ON a.siswa_id = s.id
        WHERE a.tanggal BETWEEN :start_date AND :end_date";

$params = [
    'start_date' => $start_date,
    'end_date' => $end_date
];

// Apply additional filters
if ($kelas) {
    $sql .= " AND s.kelas = :kelas";
    $params['kelas'] = $kelas;
}

if ($jurusan) {
    $sql .= " AND s.jurusan = :jurusan";
    $params['jurusan'] = $jurusan;
}

if ($siswa_id) {
    $sql .= " AND a.siswa_id = :siswa_id";
    $params['siswa_id'] = $siswa_id;
}

if ($status) {
    $sql .= " AND a.status = :status";
    $params['status'] = $status;
}

// Order by date and name
$sql .= " ORDER BY a.tanggal DESC, s.nama_lengkap ASC";

// Execute query
$stmt = $conn->prepare($sql);
foreach ($params as $key => $value) {
    $stmt->bindValue(':' . $key, $value);
}
$stmt->execute();
$data = $stmt->fetchAll(PDO::FETCH_ASSOC);

// Get summary for statistics
$summary_sql = "SELECT status, COUNT(*) as count 
                FROM absensi a 
                JOIN siswa s ON a.siswa_id = s.id
                WHERE a.tanggal BETWEEN :start_date AND :end_date";

// Apply the same filters to summary
if ($kelas) {
    $summary_sql .= " AND s.kelas = :kelas";
}

if ($jurusan) {
    $summary_sql .= " AND s.jurusan = :jurusan";
}

if ($siswa_id) {
    $summary_sql .= " AND a.siswa_id = :siswa_id";
}

if ($status) {
    $summary_sql .= " AND a.status = :status";
}

$summary_sql .= " GROUP BY status";
$summary_stmt = $conn->prepare($summary_sql);
$summary_stmt->execute($params);
$summary = $summary_stmt->fetchAll(PDO::FETCH_KEY_PAIR);

// Initialize summary counts
$status_counts = [
    'Hadir' => 0,
    'Sakit' => 0,
    'Izin' => 0,
    'Terlambat' => 0,
    'Alpha' => 0
];

// Populate with actual counts
foreach ($summary as $status => $count) {
    $status_counts[$status] = $count;
}

// Get the title with filters
$title = "Laporan Absensi";
$subtitle = "Periode: " . date('d/m/Y', strtotime($start_date)) . " - " . date('d/m/Y', strtotime($end_date));

if ($kelas) {
    $subtitle .= " | Kelas: $kelas";
}

if ($jurusan) {
    $subtitle .= " | Jurusan: $jurusan";
}

if ($siswa_id) {
    $student_sql = "SELECT nama_lengkap, nis FROM siswa WHERE id = :id";
    $student_stmt = $conn->prepare($student_sql);
    $student_stmt->execute(['id' => $siswa_id]);
    $student = $student_stmt->fetch(PDO::FETCH_ASSOC);
    if ($student) {
        $subtitle .= " | Siswa: " . $student['nama_lengkap'] . " (" . $student['nis'] . ")";
    }
}

if ($status) {
    $subtitle .= " | Status: $status";
}

// Calculate total
$total_absensi = array_sum($status_counts);

// Now handle export based on the format
if ($format === 'excel') {
    // Create new Spreadsheet
    $spreadsheet = new Spreadsheet();
    $sheet = $spreadsheet->getActiveSheet();

    // Set document properties
    $spreadsheet->getProperties()
        ->setCreator('SMA Absensi System')
        ->setLastModifiedBy('SMA Admin')
        ->setTitle($title)
        ->setSubject('Attendance Report')
        ->setDescription('Attendance report generated by hanif_tqn');

    // Set sheet title
    $sheet->setTitle('Laporan Absensi');

    // Set header with merged cells for a better layout
    $sheet->setCellValue('A1', 'LAPORAN ABSENSI SISWA');
    $sheet->setCellValue('A2', 'SMA INFORMATIKA NURUL BAYAN');
    $sheet->setCellValue('A3', $subtitle);
    $sheet->mergeCells('A1:G1');
    $sheet->mergeCells('A2:G2');
    $sheet->mergeCells('A3:G3');

    // Add generated timestamp
    $sheet->setCellValue('A4', 'Diekspor pada: ' . date('d/m/Y H:i'));
    $sheet->mergeCells('A4:G4');

    // Style the headers
    $headerStyle = [
        'font' => [
            'bold' => true,
            'size' => 16
        ],
        'alignment' => [
            'horizontal' => Alignment::HORIZONTAL_CENTER,
            'vertical' => Alignment::VERTICAL_CENTER
        ],
        'fill' => [
            'fillType' => Fill::FILL_SOLID,
            'startColor' => [
                'rgb' => 'E9ECEF'
            ]
        ],
        'borders' => [
            'bottom' => [
                'borderStyle' => Border::BORDER_MEDIUM,
                'color' => ['rgb' => '5E35B1']
            ]
        ]
    ];

    $sheet->getStyle('A1:G1')->applyFromArray($headerStyle);

    $subheaderStyle = [
        'font' => [
            'bold' => true,
            'size' => 14,
        ],
        'alignment' => [
            'horizontal' => Alignment::HORIZONTAL_CENTER,
            'vertical' => Alignment::VERTICAL_CENTER
        ]
    ];

    $sheet->getStyle('A2:G2')->applyFromArray($subheaderStyle);

    $subtitleStyle = [
        'font' => [
            'bold' => true,
            'size' => 11
        ],
        'alignment' => [
            'horizontal' => Alignment::HORIZONTAL_CENTER,
            'vertical' => Alignment::VERTICAL_CENTER
        ]
    ];

    $sheet->getStyle('A3:G3')->applyFromArray($subtitleStyle);

    $timestampStyle = [
        'font' => [
            'italic' => true,
            'size' => 10
        ],
        'alignment' => [
            'horizontal' => Alignment::HORIZONTAL_RIGHT
        ]
    ];

    $sheet->getStyle('A4:G4')->applyFromArray($timestampStyle);

    // Add more vertical space
    $sheet->getRowDimension(5)->setRowHeight(10);

    // Add summary statistics with improved styling
    $sheet->setCellValue('A6', 'RINGKASAN KEHADIRAN:');
    $sheet->mergeCells('A6:G6');

    $summaryHeaderStyle = [
        'font' => [
            'bold' => true,
            'size' => 12,
        ],
        'borders' => [
            'bottom' => [
                'borderStyle' => Border::BORDER_THIN
            ]
        ]
    ];

    $sheet->getStyle('A6:G6')->applyFromArray($summaryHeaderStyle);

    // Create a nice looking summary table
    $sheet->setCellValue('B8', 'Status');
    $sheet->setCellValue('C8', 'Jumlah');
    $sheet->setCellValue('D8', 'Persentase');

    $summaryTableHeaderStyle = [
        'font' => [
            'bold' => true
        ],
        'alignment' => [
            'horizontal' => Alignment::HORIZONTAL_CENTER
        ],
        'fill' => [
            'fillType' => Fill::FILL_SOLID,
            'startColor' => [
                'rgb' => '5E35B1'
            ]
        ],
        'font' => [
            'color' => [
                'rgb' => 'FFFFFF'
            ]
        ]
    ];

    $sheet->getStyle('B8:D8')->applyFromArray($summaryTableHeaderStyle);
    $sheet->getRowDimension(8)->setRowHeight(20);

    // Add status colors
    $statusColors = [
        'Hadir' => '10B981',     // green
        'Sakit' => 'EAB308',     // yellow
        'Izin' => '8B5CF6',      // purple
        'Terlambat' => 'F97316', // orange
        'Alpha' => 'EF4444'      // red
    ];

    // Add summary data rows with status-based styling
    $row = 9;
    foreach (['Hadir', 'Sakit', 'Izin', 'Terlambat', 'Alpha'] as $status) {
        $count = $status_counts[$status];
        $percentage = $total_absensi > 0 ? round(($count / $total_absensi) * 100, 1) . '%' : '0%';

        $sheet->setCellValue('B' . $row, $status);
        $sheet->setCellValue('C' . $row, $count);
        $sheet->setCellValue('D' . $row, $percentage);

        // Simple styling for data cells
        $dataStyle = [
            'alignment' => [
                'horizontal' => Alignment::HORIZONTAL_CENTER
            ]
        ];

        $sheet->getStyle('C' . $row . ':D' . $row)->applyFromArray($dataStyle);
        $row++;
    }

    // Add total row
    $sheet->setCellValue('B' . $row, 'TOTAL');
    $sheet->setCellValue('C' . $row, $total_absensi);
    $sheet->setCellValue('D' . $row, '100%');

    $totalStyle = [
        'font' => [
            'bold' => true
        ],
        'alignment' => [
            'horizontal' => Alignment::HORIZONTAL_CENTER
        ],
        'fill' => [
            'fillType' => Fill::FILL_SOLID,
            'startColor' => [
                'rgb' => '5E35B1'
            ]
        ],
        'font' => [
            'color' => [
                'rgb' => 'FFFFFF'
            ]
        ]
    ];

    $sheet->getStyle('B' . $row . ':D' . $row)->applyFromArray($totalStyle);

    // Add space before detail table
    $row += 2;

    // Add detail table title
    $sheet->setCellValue('A' . $row, 'DATA DETAIL KEHADIRAN');
    $sheet->mergeCells('A' . $row . ':G' . $row);
    $sheet->getStyle('A' . $row . ':G' . $row)->applyFromArray($summaryHeaderStyle);
    $row += 2;

    // Add table headers with improved styling
    $headers = ['No', 'Tanggal', 'NIS', 'Nama Siswa', 'Kelas', 'Jam Masuk', 'Status'];
    foreach ($headers as $index => $header) {
        $sheet->setCellValue(chr(65 + $index) . $row, $header);
    }

    $tableHeaderStyle = [
        'font' => [
            'bold' => true
        ],
        'alignment' => [
            'horizontal' => Alignment::HORIZONTAL_CENTER
        ],
        'fill' => [
            'fillType' => Fill::FILL_SOLID,
            'startColor' => [
                'rgb' => '5E35B1'
            ]
        ],
        'font' => [
            'color' => [
                'rgb' => 'FFFFFF'
            ]
        ]
    ];

    $sheet->getStyle('A' . $row . ':G' . $row)->applyFromArray($tableHeaderStyle);
    $sheet->getRowDimension($row)->setRowHeight(20);
    $row++;

    // Add data rows with alternating row colors
    foreach ($data as $key => $record) {
        $sheet->setCellValue('A' . $row, $key + 1);
        $sheet->setCellValue('B' . $row, date('d-m-Y', strtotime($record['tanggal'])));
        $sheet->setCellValue('C' . $row, $record['nis']);
        $sheet->setCellValue('D' . $row, $record['nama_lengkap']);
        $sheet->setCellValue('E' . $row, $record['kelas'] . ' ' . $record['jurusan']);
        $sheet->setCellValue('F' . $row, $record['jam_masuk'] !== '00:00:00' ? date('H:i', strtotime($record['jam_masuk'])) : '-');
        $sheet->setCellValue('G' . $row, $record['status']);

        $row++;
    }

    // Set column widths for better readability
    $sheet->getColumnDimension('A')->setWidth(6);  // No
    $sheet->getColumnDimension('B')->setWidth(15); // Tanggal
    $sheet->getColumnDimension('C')->setWidth(15); // NIS
    $sheet->getColumnDimension('D')->setWidth(30); // Nama
    $sheet->getColumnDimension('E')->setWidth(15); // Kelas
    $sheet->getColumnDimension('F')->setWidth(15); // Jam Masuk
    $sheet->getColumnDimension('G')->setWidth(15); // Status

    // Add footer
    $row += 2;
    $sheet->setCellValue('A' . $row, 'Laporan ini digenerate secara otomatis dari Sistem Absensi SMKN 40 Jakarta');
    $sheet->mergeCells('A' . $row . ':G' . $row);

    $sheet->getStyle('A' . $row)->applyFromArray([
        'font' => [
            'italic' => true
        ],
        'alignment' => [
            'horizontal' => Alignment::HORIZONTAL_CENTER
        ]
    ]);

    // Create Excel file - REMOVED chart functionality as it might be causing issues
    $writer = new Xlsx($spreadsheet);

    // Set headers for download
    header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    header('Content-Disposition: attachment;filename="Laporan_Absensi_' . date('Y-m-d') . '.xlsx"');
    header('Cache-Control: max-age=0');

    // Save to output
    $writer->save('php://output');
    exit;
} else {
    // PDF Export using dompdf with enhanced styling
    // Configure Dompdf
    $options = new Options();
    $options->set('isHtml5ParserEnabled', true);
    $options->set('isRemoteEnabled', true);
    $options->set('defaultFont', 'Helvetica');
    $options->set('chroot', $_SERVER['DOCUMENT_ROOT']); // For local image access

    $dompdf = new Dompdf($options);

    // Base path for logo (adjust based on actual logo location)
    $logoPath = $_SERVER['DOCUMENT_ROOT'] . '/assets/default/logo-sma.png';
    // Use data URI scheme for the logo if available
    $logoData = '';
    if (file_exists($logoPath)) {
        $logoData = 'data:image/png;base64,' . base64_encode(file_get_contents($logoPath));
    }

    // Start building the HTML content with enhanced styling
    $html = '
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Laporan Absensi</title>
        <style>
            @page {
                margin: 20mm 15mm 20mm 15mm;
            }
            body {
                font-family: Helvetica, Arial, sans-serif;
                line-height: 1.4;
                color: #333;
                margin: 0;
                padding: 0;
                background-color: #fff;
            }
            .header {
                text-align: center;
                margin-bottom: 20px;
                border-bottom: 2px solid #5E35B1;
                padding-bottom: 10px;
            }
            .header-content {
                display: flex;
                align-items: center;
                justify-content: center;
                margin-bottom: 10px;
            }
            .logo {
                height: 60px;
                margin-right: 15px;
            }
            .header-text {
                text-align: center;
            }
            .header h1 {
                font-size: 20px;
                margin: 5px 0;
                color: #5E35B1;
            }
            .header h2 {
                font-size: 16px;
                margin: 5px 0;
                color: #333;
            }
            .subtitle {
                font-size: 14px;
                color: #555;
                margin: 5px 0;
                text-align: center;
            }
            table {
                width: 100%;
                border-collapse: collapse;
                margin: 15px 0;
                font-size: 11px;
            }
            table, th, td {
                border: 1px solid #dee2e6;
            }
            th, td {
                padding: 8px;
                text-align: left;
            }
            th {
                background-color: #5E35B1;
                color: white;
                font-weight: bold;
                font-size: 12px;
                text-align: center;
            }
            .summary-table {
                margin-bottom: 20px;
            }
            .summary-table th {
                width: 150px;
            }
            .text-center {
                text-align: center;
            }
            .text-right {
                text-align: right;
            }
            .section {
                margin-bottom: 25px;
            }
            .section-title {
                font-size: 16px;
                font-weight: bold;
                margin-bottom: 10px;
                padding: 5px 0;
                border-bottom: 1px solid #5E35B1;
                color: #5E35B1;
            }
            .status-hadir { color: #10B981; }
            .status-sakit { color: #EAB308; }
            .status-izin { color: #8B5CF6; }
            .status-terlambat { color: #F97316; }
            .status-alpha { color: #EF4444; }
            
            /* Summary cards styling */
            .summary-card {
                background-color: #f8f9fa;
                border-radius: 8px;
                padding: 10px;
                margin-bottom: 15px;
                border-left: 4px solid #5E35B1;
            }
            .summary-grid {
                display: grid;
                grid-template-columns: repeat(2, 1fr);
                gap: 15px;
                margin-bottom: 20px;
            }
            .card {
                padding: 10px;
                border-radius: 5px;
                text-align: center;
            }
            .card-hadir {
                background-color: rgba(16, 185, 129, 0.1);
                border: 1px solid #10B981;
            }
            .card-sakit {
                background-color: rgba(234, 179, 8, 0.1);
                border: 1px solid #EAB308;
            }
            .card-izin {
                background-color: rgba(139, 92, 246, 0.1);
                border: 1px solid #8B5CF6;
            }
            .card-terlambat {
                background-color: rgba(249, 115, 22, 0.1);
                border: 1px solid #F97316;
            }
            .card-alpha {
                background-color: rgba(239, 68, 68, 0.1);
                border: 1px solid #EF4444;
            }
            .card-label {
                font-size: 12px;
                color: #666;
                margin-bottom: 5px;
            }
            .card-value {
                font-size: 18px;
                font-weight: bold;
            }
            .card-percentage {
                font-size: 11px;
                color: #888;
                margin-top: 3px;
            }
            
            /* Table row striping */
            tr:nth-child(even) {
                background-color: #f9f9f9;
            }
            
            .footer {
                margin-top: 30px;
                text-align: center;
                font-size: 11px;
                color: #555;
                border-top: 1px solid #dee2e6;
                padding-top: 10px;
            }
            .footer p {
                margin: 5px 0;
            }
            
            /* Page number styling */
            .page-number {
                text-align: center;
                font-size: 10px;
                color: #777;
                margin-top: 15px;
            }
            
            /* Print date */
            .print-date {
                text-align: right;
                font-size: 10px;
                font-style: italic;
                color: #777;
                margin-bottom: 10px;
            }
        </style>
    </head>
    <body>
        <div class="header">
            <div class="header-content">
                <img class="logo" src="' . $logoData . '" alt="SMA Informatika Nurul Bayan">
                <div class="header-text">
                    <h1>LAPORAN ABSENSI SISWA</h1>
                    <h2>SMA INFORMATIKA NURUL BAYAN</h2>
                </div>
            </div>
        </div>
        <p class="subtitle">' . $subtitle . '</p>
        <p class="print-date">Diekspor pada: ' . date('d/m/Y H:i') . '</p>
        
        <div class="section">
            <div class="section-title">RINGKASAN KEHADIRAN</div>
            
            <div class="summary-grid">';

    // Add summary cards with status-based styling
    $statusLabels = [
        'Hadir' => 'card-hadir',
        'Sakit' => 'card-sakit',
        'Izin' => 'card-izin',
        'Terlambat' => 'card-terlambat',
        'Alpha' => 'card-alpha'
    ];

    foreach ($statusLabels as $status => $cardClass) {
        $count = $status_counts[$status];
        $percentage = $total_absensi > 0 ? round(($count / $total_absensi) * 100, 1) . '%' : '0%';

        $html .= '
            <div class="card ' . $cardClass . '">
                <div class="card-label">' . $status . '</div>
                <div class="card-value">' . $count . '</div>
                <div class="card-percentage">' . $percentage . '</div>
            </div>';
    }

    $html .= '
            </div>
            <div class="summary-card">
                <table class="summary-table">
                    <tr>
                        <th>Status</th>
                        <th>Jumlah</th>
                        <th>Persentase</th>
                    </tr>';

    // Add status rows
    foreach (['Hadir', 'Sakit', 'Izin', 'Terlambat', 'Alpha'] as $status_key) {
        $count = $status_counts[$status_key];
        $percentage = $total_absensi > 0 ? round(($count / $total_absensi) * 100, 1) . '%' : '0%';
        $html .= '
                    <tr>
                        <td><span class="status-' . strtolower($status_key) . '">' . $status_key . '</span></td>
                        <td class="text-center">' . $count . '</td>
                        <td class="text-center">' . $percentage . '</td>
                    </tr>';
    }

    // Add total row
    $html .= '
                    <tr style="background-color: #5E35B1; color: white; font-weight: bold;">
                        <td>Total</td>
                        <td class="text-center">' . $total_absensi . '</td>
                        <td class="text-center">100%</td>
                    </tr>
                </table>
            </div>
        </div>
        
        <div class="section">
            <div class="section-title">DETAIL ABSENSI</div>';

    // Check if we have data
    if (count($data) > 0) {
        $html .= '
            <table>
                <tr>
                    <th>No</th>
                    <th>Tanggal</th>
                    <th>NIS</th>
                    <th>Nama</th>
                    <th>Kelas</th>
                    <th>Jam Masuk</th>
                    <th>Status</th>
                </tr>';

        // Data rows
        $no = 1;
        foreach ($data as $row) {
            $status_class = 'status-' . strtolower($row['status']);
            $html .= '
                <tr>
                    <td class="text-center">' . $no . '</td>
                    <td class="text-center">' . date('d/m/Y', strtotime($row['tanggal'])) . '</td>
                    <td>' . $row['nis'] . '</td>
                    <td>' . htmlspecialchars($row['nama_lengkap']) . '</td>
                    <td class="text-center">' . $row['kelas'] . ' ' . $row['jurusan'] . '</td>
                    <td class="text-center">' . ($row['jam_masuk'] !== '00:00:00' ? date('H:i', strtotime($row['jam_masuk'])) : '-') . '</td>
                    <td class="text-center"><span class="' . $status_class . '">' . $row['status'] . '</span></td>
                </tr>';
            $no++;
        }

        $html .= '
            </table>';
    } else {
        $html .= '
            <p class="text-center">Tidak ada data yang ditemukan untuk filter yang dipilih.</p>';
    }

    $html .= '
        </div>
        
        <div class="footer">
            <p>Cimerak, ' . date('d F Y') . '</p>
            <p>_____________________</p>
            <p>Admin Absen SMA</p>
            <p class="page-number">Halaman <span class="pagenum"></span></p>
        </div>
    </body>
    </html>';

    // Load HTML content into Dompdf
    $dompdf->loadHtml($html);

    // Set paper size and orientation
    $dompdf->setPaper('A4', 'portrait');

    // Render PDF
    $dompdf->render();

    // Add page number
    $canvas = $dompdf->getCanvas();
    $canvas->page_script(function ($pageNumber, $pageCount, $canvas, $fontMetrics) {
        $text = "Halaman $pageNumber dari $pageCount";
        $size = 10;
        $font = $fontMetrics->getFont("Helvetica");
        $width = $fontMetrics->getTextWidth($text, $font, $size);
        $canvas->text(($canvas->get_width() - $width) / 2, $canvas->get_height() - 35, $text, $font, $size);
    });

    // Output the generated PDF to Browser
    $dompdf->stream("Laporan_Absensi_" . date('Y-m-d') . ".pdf", array("Attachment" => true));
    exit;
}
